name: Generate Sitemap

on:
  push:
    branches:
      - main  # o el nombre de la rama principal que uses
  pull_request:
    branches:
      - main  # también en las solicitudes de pull

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate Sitemap
      run: |
        echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > sitemap.xml
        echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" >> sitemap.xml
        echo "  <url>" >> sitemap.xml
        echo "    <loc>https://derutanotame.github.io/Nageki-No-Boure-Wa-Intai-Shitai-Novela-Volumen-7/</loc>" >> sitemap.xml
        echo "  </url>" >> sitemap.xml
        echo "</urlset>" >> sitemap.xml

    - name: Commit Sitemap
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'Generar sitemap.xml automáticamente'
